### PR TITLE
Fix combined experiments

### LINKED ISSUE #500: Q: How to get the bucket of  `combined_experiments` ?
When you, eg.
```ruby
  Split.configuration.experiments = {
        :button_color_experiment => {
          :alternatives => ["blue", "green"],
          :combined_experiments => ["button_color_on_signup", "button_color_on_login"]
        }
      }

thing =  ab_combined_test(:button_color_experiment)
```
After you run `ab_combined_test` how can you know whether you are in the `blue` or `green` bucket (and decide what color to actually draw the button) ?
In this snippet, `thing` gets the value of `["button_color_on_signup", "button_color_on_login"]
`, which is actually the result of the `each` method [here](https://github.com/splitrb/split/blob/master/lib/split/combined_experiments_helper.rb#L9)

### PR DESCRIPTION
**Pull request by semanticart**
1. always pass all alternatives to prevent unintentional version bumps
2. return the chosen alternative from `ab_combined_test`

Fixes #500

### CODE REVIEW

File: lib/split/combined_experiments_helper.rb [hunk 1]
```diff
@@ -15,9 +16,15 @@ def ab_combined_test(metric_descriptor, control = nil, *alternatives)
             alternative = ab_test(combined_experiment, normalized_alternatives[0], *normalized_alternatives[1])
           end
         else
-          ab_test(combined_experiment, [{alternative => 1}])
+          weighted_alternatives ||= experiment[:alternatives].each_with_object({}) do |alt, memo|
+            alt = Alternative.new(alt, experiment[:name]).name
+            memo[alt] = (alt == alternative ? 1 : 0)
+          end
```
Comment (semanticart) [inline lib/split/combined_experiments_helper.rb]: If there's a better way to do this, I'm all ears.

The goal is to return an array with a hash that has each alternative with a weight of zero except the selected alternative which should have a weight of 1.

e.g. `[{"control" => 0, "test-alt" => 1}]`

Because `experiment[:alternatives]` can be a simple array or a hash of weights, I'm leaning on `Alternative` to normalize the name.

**Comment by andrew** [comment]
LGTM 👍

**Comment by semanticart** [comment]
Awesome 👏  Merge when ready.

**Comment by andrew** [comment]
I’ll get a new release published to rubygems tomorrow 👌

**Comment by daviddening** [comment]
@semanticart  Thanks for fixing this

**Comment by semanticart** [comment]
@daviddening thanks for the original feature work.

@andrew thanks for the new release. <3

**Comment by andrew** [comment]
🚢  in 3.2.0: https://github.com/splitrb/split/releases/tag/v3.2.0
